import "./globals.css"
import Footer from './_components/shared/Footer/Footer'
import Header from './_components/shared/Header/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en' data-arp="">
      <body cz-shortcut-listen="true" className="max-w-6xl mx-auto">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
